Do: false
path: "/home/roit/datasets/sn/stk-gen/starlink/harbin"
dump_stem: "100Cno(dBHz)"
assigned_units: ['Range (km)']# 处理的unit


files: ["range.dat"]

access_shuffle: true
access_portion: [0,1] #[0,0.6]
time_duration: [0.1,0.112]



random_seed: 1234





#alg
algorithm: 'mst' #mea,mst,greedy,dp

input_metrics: ['Range (km)']



output_metrics: ['Cno(dBHz)']
#output_metrics: ['Pr(dBW)']
#output_metrics: ['CN(dB)','CT(dBW/K)','CT(W/K)']


algorithm_base: ['Cno(dBHz)']
#algorithm_base: ['Pr(dBW)']


data_show_lines: ['Time (second)','Cno(dBHz)']
#data_show_lines: ['time','Pr(dBW)']

#save
save: false
